### PR TITLE
Changes to match new AM programming model

### PR DESCRIPTION
**Pull request by sfitts**
The E2E streaming changes required some changes to the AM code.

Also some examples for bulk loading.

### CODE REVIEW

**Comment by brian717** [comment]
@sfitts I guess at this point, it doesn't make sense to merge this one in?

**Comment by sfitts** [comment]
@brian717 honestly, I couldn't tell you :)   just noticed this somewhat by accident and figured I should put it to bed.  If the code is still in use and someone thinks the changes are worth it, by all means merge away.

**Comment by brian717** [comment]
haha, nope was just kidding. I figured this was long dead. Hope everything's great on your end!

**Comment by sfitts** [comment]
phew!  I have to say that I almost fell out of my chair when someone responded to this.  Things are good here -- hope you are the same (and staying safe).

**Comment by yellowBirdy** [comment]
Wow. That sure was a surprise :). Good to hear you two are doing good.

**Pull request closed without merging**
